# Generated by Django 4.1.4 on 2023-01-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('area', models.FloatField()),
                ('price', models.FloatField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
